package cn.myrealm.customarcheology.hooks.craftengine;

import cn.myrealm.customarcheology.CustomArcheology;
import cn.myrealm.customarcheology.managers.managers.system.TextureManager;
import cn.myrealm.customarcheology.mechanics.cores.BlockMode;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.Plugin;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.stream.Stream;

public class CraftEngineResourceInstaller {
    private static final String PACK_NAME = "customarcheology";

    private final CustomArcheology plugin;

    public CraftEngineResourceInstaller(CustomArcheology plugin) {
        this.plugin = plugin;
    }

    public int install() throws IOException {
        if (plugin.getBlockMode() != BlockMode.CRAFTENGINE) {
            return 0;
        }
        Plugin craftEngine = plugin.getServer().getPluginManager().getPlugin("CraftEngine");
        if (craftEngine == null) {
            throw new IllegalStateException("CraftEngine is not installed");
        }
        Path packFolder = craftEngine.getDataFolder().toPath().resolve("resources").resolve(PACK_NAME);
        Path configurationFolder = packFolder.resolve("configuration");
        Path resourcePackFolder = packFolder.resolve("resourcepack");
        Path textureFolder = resourcePackFolder.resolve("assets")
                .resolve(PACK_NAME).resolve("textures").resolve("block");
        Files.createDirectories(configurationFolder);
        Files.createDirectories(textureFolder);
        writePackDescription(packFolder);
        copyResourcePack(resourcePackFolder);

        File[] blockFileArray = new File(plugin.getDataFolder(), "blocks")
                .listFiles(file -> file.isFile() && file.getName().endsWith(".yml"));
        if (blockFileArray == null) {
            throw new IOException("Could not read CustomArcheology blocks folder");
        }
        List<File> blockFiles = new ArrayList<>(List.of(blockFileArray));
        blockFiles.sort(Comparator.comparing(File::getName));
        File[] toolFileArray = new File(plugin.getDataFolder(), "tools")
                .listFiles(file -> file.isFile() && file.getName().endsWith(".yml"));
        if (toolFileArray == null) {
            throw new IOException("Could not read CustomArcheology tools folder");
        }
        List<File> toolFiles = new ArrayList<>(List.of(toolFileArray));
        toolFiles.sort(Comparator.comparing(File::getName));

        StringBuilder output = new StringBuilder();
        output.append("# Generated by CustomArcheology. Changes are replaced on server startup.\n");
        output.append("items:\n");
        int installed = 0;
        for (File blockFile : blockFiles) {
            YamlConfiguration config = YamlConfiguration.loadConfiguration(blockFile);
            if (!config.getBoolean("craftengine.auto-install", true)) {
                continue;
            }
            appendItem(output, blockFile, config);
            installed++;
        }
        Path toolTextureFolder = resourcePackFolder.resolve("assets").resolve(PACK_NAME)
                .resolve("textures").resolve("item");
        Path toolModelFolder = resourcePackFolder.resolve("assets").resolve(PACK_NAME)
                .resolve("models").resolve("item");
        for (File toolFile : toolFiles) {
            YamlConfiguration config = YamlConfiguration.loadConfiguration(toolFile);
            if (!config.getBoolean("craftengine.auto-install", true)) {
                continue;
            }
            appendTool(output, toolFile, config, toolTextureFolder, toolModelFolder);
        }
        output.append("\nblocks:\n");
        for (File blockFile : blockFiles) {
            YamlConfiguration config = YamlConfiguration.loadConfiguration(blockFile);
            if (!config.getBoolean("craftengine.auto-install", true)) {
                continue;
            }
            appendBlock(output, blockFile, config, textureFolder);
        }
        Files.writeString(configurationFolder.resolve("customarcheology-generated.yml"), output,
                StandardCharsets.UTF_8);
        return installed;
    }

    private void writePackDescription(Path packFolder) throws IOException {
        Path packFile = packFolder.resolve("pack.yml");
        if (Files.exists(packFile)) {
            return;
        }
        String content = "author: CustomArcheology\n"
                + "description: Auto-generated CustomArcheology blocks\n"
                + "version: '1.0'\n"
                + "namespace: customarcheology\n"
                + "enable: true\n";
        Files.writeString(packFile, content, StandardCharsets.UTF_8);
    }

    private void appendItem(StringBuilder output, File file, YamlConfiguration config) {
        String blockId = getBlockId(file, config);
        String itemId = config.getString("craftengine.item", blockId);
        String texture = getStageTexture(config, "default");
        output.append("  ").append(itemId).append(":\n")
                .append("    material: paper\n")
                .append("    data:\n")
                .append("      item_name: ").append(quote(component(getString(config,
                        "general.display-name", "general.display_name", title(getId(file)))))).append("\n")
                .append("    model:\n")
                .append("      type: minecraft:model\n")
                .append("      path: customarcheology:block/").append(texture).append("\n")
                .append("    behavior:\n")
                .append("      type: block_item\n")
                .append("      block: ").append(blockId).append("\n");
    }

    private void appendTool(StringBuilder output, File file, YamlConfiguration config,
                            Path textureFolder, Path modelFolder) throws IOException {
        String toolId = getId(file);
        String itemId = config.getString("craftengine.item", PACK_NAME + ":" + toolId);
        String texture = config.getString("texture", toolId);
        output.append("  ").append(itemId).append(":\n")
                .append("    material: brush\n")
                .append("    data:\n")
                .append("      item_name: ").append(quote(component(config.getString(
                        "display-name", title(toolId))))).append("\n");
        List<String> lore = config.getStringList("lore");
        if (!lore.isEmpty()) {
            output.append("      lore:\n");
            for (String line : lore) {
                output.append("        - ").append(quote(component(line))).append("\n");
            }
        }
        output.append("    model:\n")
                .append("      type: minecraft:range_dispatch\n")
                .append("      property: minecraft:use_cycle\n")
                .append("      source: 10\n")
                .append("      period: 10\n")
                .append("      scale: 0.1\n")
                .append("      fallback:\n")
                .append("        type: minecraft:model\n")
                .append("        path: customarcheology:item/").append(texture).append("\n")
                .append("      entries:\n");
        int[] stages = {0, 6, 7, 8, 9, 10, 9, 8, 7, 6, 0, 1, 2, 3, 4, 5, 4, 3, 2, 1, 0};
        for (int i = 0; i < stages.length; i++) {
            output.append("        - threshold: ").append(i / 20.0).append("\n")
                    .append("          model:\n")
                    .append("            type: minecraft:model\n")
                    .append("            path: customarcheology:item/").append(texture)
                    .append("_").append(stages[i]).append("\n");
        }
        output.append("    legacy_model:\n")
                .append("      path: customarcheology:item/").append(texture).append("\n")
                .append("      overrides:\n");
        for (int i = 0; i < stages.length; i++) {
            output.append("        - path: customarcheology:item/").append(texture)
                    .append("_").append(stages[i]).append("\n")
                    .append("          predicate:\n")
                    .append("            brushing: ").append(i / 20.0).append("\n");
        }
        copyToolTexture(texture, textureFolder);
        TextureManager.outputToolModels(modelFolder, texture);
    }

    private void appendBlock(StringBuilder output, File file, YamlConfiguration config,
                             Path textureFolder) throws IOException {
        String archeologyId = file.getName().substring(0, file.getName().length() - 4);
        String blockId = getBlockId(file, config);
        String itemId = config.getString("craftengine.item", blockId);
        ConfigurationSection states = Objects.requireNonNull(config.getConfigurationSection("states"),
                "Missing states in " + file.getName());
        List<String> stateNames = states.getKeys(false).stream()
                .filter(name -> !name.equals("finished"))
                .sorted(Comparator.comparingInt(this::getStateIndex))
                .toList();
        if (stateNames.isEmpty() || !stateNames.get(0).equals("default")) {
            throw new IllegalArgumentException("Missing default state in " + file.getName());
        }

        output.append("  ").append(blockId).append(":\n")
                .append("    settings:\n")
                .append("      item: ").append(itemId).append("\n")
                .append("      hardness: ").append(config.getDouble(
                        "states.default.hardness", 1.0)).append("\n")
                .append("      resistance: 6.0\n")
                .append("      sounds:\n")
                .append("        place: ").append(sound(getString(config, "general.sound.place",
                        "general.sound.place", "BLOCK_STONE_PLACE"))).append("\n")
                .append("        break: minecraft:block.stone.break\n")
                .append("        hit: minecraft:block.stone.hit\n")
                .append("        step: minecraft:block.stone.step\n")
                .append("        fall: minecraft:block.stone.fall\n")
                .append("    behavior:\n")
                .append("      type: customarcheology:brushable\n")
                .append("      archeology-id: ").append(archeologyId).append("\n")
                .append("      replace-block: ").append(getString(config,
                        "general.replace-block", "general.replace_block", "stone")).append("\n")
                .append("      progress-property: dusted\n")
                .append("    states:\n")
                .append("      properties:\n")
                .append("        dusted:\n")
                .append("          type: int\n")
                .append("          range: 0~").append(stateNames.size() - 1).append("\n")
                .append("          default: 0\n")
                .append("      appearances:\n");
        for (int i = 0; i < stateNames.size(); i++) {
            String texture = getStageTexture(config, stateNames.get(i));
            copyTexture(texture, textureFolder);
            output.append("        stage_").append(i).append(":\n")
                    .append("          auto_state: solid\n")
                    .append("          model:\n")
                    .append("            path: customarcheology:block/").append(texture).append("\n")
                    .append("            generation:\n")
                    .append("              parent: minecraft:block/cube_all\n")
                    .append("              textures:\n")
                    .append("                all: customarcheology:block/").append(texture).append("\n");
        }
        output.append("      variants:\n");
        for (int i = 0; i < stateNames.size(); i++) {
            output.append("        dusted=").append(i).append(":\n")
                    .append("          appearance: stage_").append(i).append("\n");
        }
    }

    private String getBlockId(File file, YamlConfiguration config) {
        String archeologyId = getId(file);
        return config.getString("craftengine.block", "customarcheology:" + archeologyId);
    }

    private String getId(File file) {
        return file.getName().substring(0, file.getName().length() - 4);
    }

    private String getStageTexture(YamlConfiguration config, String state) {
        String texture = config.getString("states." + state + ".texture");
        if (texture == null || texture.isBlank()) {
            throw new IllegalArgumentException("Missing texture for state " + state);
        }
        return texture;
    }

    private int getStateIndex(String state) {
        if (state.equals("default")) {
            return 0;
        }
        try {
            return Integer.parseInt(state.substring(state.lastIndexOf('_') + 1));
        } catch (NumberFormatException exception) {
            throw new IllegalArgumentException("Invalid state name: " + state);
        }
    }

    private void copyTexture(String texture, Path targetFolder) throws IOException {
        Path source = plugin.getDataFolder().toPath().resolve("textures").resolve("blocks")
                .resolve(texture + ".png");
        if (!Files.isRegularFile(source)) {
            throw new IOException("Missing block texture: " + source);
        }
        Files.copy(source, targetFolder.resolve(texture + ".png"), StandardCopyOption.REPLACE_EXISTING);
        Path metadata = source.resolveSibling(source.getFileName() + ".mcmeta");
        if (Files.isRegularFile(metadata)) {
            Files.copy(metadata, targetFolder.resolve(texture + ".png.mcmeta"),
                    StandardCopyOption.REPLACE_EXISTING);
        }
    }

    private void copyToolTexture(String texture, Path targetFolder) throws IOException {
        Files.createDirectories(targetFolder);
        Path source = plugin.getDataFolder().toPath().resolve("textures").resolve("tools")
                .resolve(texture + ".png");
        if (!Files.isRegularFile(source)) {
            throw new IOException("Missing tool texture: " + source);
        }
        Files.copy(source, targetFolder.resolve(texture + ".png"), StandardCopyOption.REPLACE_EXISTING);
        Path metadata = source.resolveSibling(source.getFileName() + ".mcmeta");
        if (Files.isRegularFile(metadata)) {
            Files.copy(metadata, targetFolder.resolve(texture + ".png.mcmeta"),
                    StandardCopyOption.REPLACE_EXISTING);
        }
    }

    private void copyResourcePack(Path targetFolder) throws IOException {
        Path sourceFolder = plugin.getDataFolder().toPath().resolve("pack");
        if (!Files.isDirectory(sourceFolder)) {
            return;
        }
        try (Stream<Path> paths = Files.walk(sourceFolder)) {
            for (Path source : paths.toList()) {
                Path relative = sourceFolder.relativize(source);
                if (isLegacyDispatcher(relative)) {
                    continue;
                }
                Path target = targetFolder.resolve(relative);
                if (Files.isDirectory(source)) {
                    Files.createDirectories(target);
                } else {
                    Files.createDirectories(target.getParent());
                    Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
                }
            }
        }
    }

    private boolean isLegacyDispatcher(Path relative) {
        String path = relative.toString().replace('\\', '/').toLowerCase(java.util.Locale.ROOT);
        String blockMaterial = plugin.getConfig().getString("settings.block-material", "STONE")
                .toLowerCase(java.util.Locale.ROOT);
        return path.equals("assets/minecraft/models/item/brush.json")
                || path.equals("assets/minecraft/items/brush.json")
                || path.equals("assets/minecraft/models/item/" + blockMaterial + ".json")
                || path.equals("assets/minecraft/items/" + blockMaterial + ".json");
    }

    private String title(String id) {
        StringBuilder result = new StringBuilder();
        for (String word : id.split("_")) {
            if (!word.isEmpty()) {
                result.append(Character.toUpperCase(word.charAt(0)))
                        .append(word.substring(1)).append(' ');
            }
        }
        return result.toString().trim();
    }

    private String getString(YamlConfiguration config, String primary, String legacy,
                             String defaultValue) {
        String value = config.getString(primary);
        if (value == null) {
            value = config.getString(legacy);
        }
        return value == null ? defaultValue : value;
    }

    private String sound(String value) {
        String sound = value.toLowerCase(java.util.Locale.ROOT);
        if (sound.indexOf(':') < 0) {
            sound = "minecraft:" + sound.replace('_', '.');
        }
        return sound;
    }

    private String component(String value) {
        String result = value == null ? "" : value;
        String[] colors = {"black", "dark_blue", "dark_green", "dark_aqua", "dark_red",
                "dark_purple", "gold", "gray", "dark_gray", "blue", "green", "aqua", "red",
                "light_purple", "yellow", "white"};
        String codes = "0123456789abcdef";
        for (int i = 0; i < codes.length(); i++) {
            result = result.replace("&" + codes.charAt(i), "<" + colors[i] + ">")
                    .replace("§" + codes.charAt(i), "<" + colors[i] + ">");
        }
        return result.replace("&l", "<bold>").replace("§l", "<bold>")
                .replace("&o", "<italic>").replace("§o", "<italic>")
                .replace("&n", "<underlined>").replace("§n", "<underlined>")
                .replace("&m", "<strikethrough>").replace("§m", "<strikethrough>")
                .replace("&k", "<obfuscated>").replace("§k", "<obfuscated>")
                .replace("&r", "<reset>").replace("§r", "<reset>");
    }

    private String quote(String value) {
        return "'" + value.replace("'", "''") + "'";
    }
}
